apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
        - name: load-balancer
          image: ghcr.io/tunahancan/load-balancer:latest
          ports:
            - name: tcp
              containerPort: 12000
          volumeMounts:
            - name: config
              mountPath: /etc/load-balancer
              readOnly: true
          # Eğer program config path env ile seçiyorsa ekleriz:
          # env:
          #   - name: CONFIG_PATH
          #     value: /etc/load-balancer/application.properties
      volumes:
        - name: config
          configMap:
            name: load-balancer-config
            items:
              - key: application.properties
                path: application.properties
