apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: apps
spec:
  type: NodePort
  selector:
    app: load-balancer
  ports:
    - name: tcp
      port: 12000
      targetPort: 12000
      nodePort: 30120
