apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - headless.yaml

images:
  - name: ghcr.io/tunahancan/can-cache-agent
    newTag: latest
